language: general
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
            - nasm
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0
#        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - nasm
      env:
        - CC=gcc-6
        - CXX=g++-6
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

#before_install (Add a :)
#  - eval "${MATRIX_EVAL}"

script:
  - make
  - make prelude
