language: general
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-6
            - nasm
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - nasm
      env:
        - CC=gcc-6
        - CXX=g++-6

script:
  - make TIER="CI"
  - make prelude
