#!/usr/bin/env python

# Copyright (C) 2017, Isaac Woods.
# See LICENCE.md

from __future__ import print_function
import re
import os
import glob

HEADER=br'''/*
 * Generated source-code is not an original literary work, and so this one file is distributed under CC-BY-SA, not the license in LICENSE.md
 *
 * --- THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE MODIFIED, AS IT WILL JUST BE OVERWRITTEN ---
 */

#include <ast.hpp>

'''

with open('src/auto_doAstPasses.cpp', 'wb') as f:
    f.write(HEADER)

    for astPass in glob.glob('src/PASS_*.hpp'):
        f.write('#include <{}>\n'.format(astPass[(astPass.find('/')+1):]))

    f.write(br'''
error_state ApplyASTPasses(parse_result& parse, thing_of_code* code, node* n)
{
  error_state errorState = CreateErrorState(TRAVERSING_AST, code, n);
''')

    for astPass in glob.glob('src/PASS_*.hpp'):
        f.write('  ApplyPassToNode(n, code, {}, parse, errorState);\n'.format(astPass[(astPass.find('/')+1):(astPass.find('.'))]))

    f.write(br'''  return errorState;
}''')
