/*
 * Generated source-code is not an original literary work, and so this one file is distributed under CC-BY-SA, not the license in LICENSE.md
 *
 * --- THIS FILE IS AUTOMATICALLY GENERATED AND SHOULD NOT BE MODIFIED, AS IT WILL JUST BE OVERWRITTEN ---
 */

#include <ast.hpp>

#include <PASS_constantFolder.hpp>
#include <PASS_typeChecker.hpp>
#include <PASS_resolveVars.hpp>

#define DO_PASS(astPass)\
  ApplyPassToNode(n, code, astPass, parse, errorState);\
  if (errorState.hasErrored) return errorState;

error_state ApplyASTPasses(parse_result& parse, thing_of_code* code, node* n)
{
  error_state errorState = CreateErrorState(TRAVERSING_AST, code, n);

  DO_PASS(PASS_resolveVars);
  DO_PASS(PASS_typeChecker);
  DO_PASS(PASS_constantFolder);

  return errorState;
}
