/*
 * Generated source-code is not an original literary work, and so this is distributed under CC-BY-SA.
 *
 * --- THIS FILE IS AUTOMATICALLY GENERATED AND SO SHOULD NOT BE MODIFIED, AS IT WILL JUST BE OVERWRITTEN ---
 */

#include <ast.hpp>

#include <PASS_constantFolder.hpp>
#include <PASS_typeChecker.hpp>
#include <PASS_resolveVars.hpp>

error_state ApplyASTPasses(parse_result& parse, thing_of_code* code, node* n)
{
  error_state errorState = CreateErrorState(TRAVERSING_AST, code, n);
  ApplyPassToNode(n, code, PASS_constantFolder, parse, errorState);
  ApplyPassToNode(n, code, PASS_typeChecker, parse, errorState);
  ApplyPassToNode(n, code, PASS_resolveVars, parse, errorState);
  return errorState;
}